- hosts: windowshosts
  become: true
  become_user: User
  tasks:
  - name: install Win32-OpenSSH
    win_chocolatey:
      name: openssh
      package_params: /SSHServerFeature /SSHAgentFeature
      state: present
