all:
  children:
    windowshosts:
      hosts:
        137.135.89.156
      vars:
        ansible_user: <user_from_azure_vm_creation>
        ansible_password: <pwd_from_azure_vm_creation>
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_scheme: https
        ansible_port: 5986
