all:
  children:
    windowshosts:
      hosts:
        WinDev1910Eval
      vars:
        ansible_user: User
        ansible_password: ansible
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_scheme: http
        ansible_port: 5985
        
